import type { Metadata } from "next";
import { Almarai } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
// ================================================================
const almarai = Almarai({
  subsets: ["arabic"],
  weight: ["300", "400", "700", "800"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${almarai.className}  h-full`}>
      <body
        dir="rtl"
        className="min-h-full flex flex-col bg-linear-to-r to-indigo-900 from-pink-900"
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
